language: haskell
before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update
  - mkdir lens
  - git clone https://github.com/ekmett/lens.git
  - cd lens
  - travis/cabal-apt-install
  - cabal install
  - cd ..
  - travis/cabal-apt-install --enable-tests

install:
  - cabal install

script:
  - cabal install --enable-tests
  - hlint src --cpp-define HLINT || true # don't fail for hlint

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313analytics\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
