language: haskell
before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update
  - mkdir lens
  - git clone https://github.com/ekmett/lens.git
  - cd lens
  - travis/cabal-apt-install --constraint='hashable >= 1.2' --constraint='vector >= 0.10.0.1'
  - cabal install
  - cd ..
  - travis/cabal-apt-install $mode

install:
  - cabal configure $mode
  - cabal build

script:
  - $script && hlint src --cpp-define HLINT

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313analytics\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"

env:
  - mode="--enable-tests -v" script="cabal test"
